spring:
    application:
        name: DJungleAcademy
    datasource:
        password: admin
        url: jdbc:postgresql://localhost:5432/JungleAcademy
        username: postgres
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create
        show-sql: true
    sql:
        init:
            mode: always
    thymeleaf:
        cache: false
    jwt:
        secret: HelloWorld # 使用更复杂的密钥
        expiration: 600000 # 10 分钟，以毫秒为单位
